apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: s3-fuse-flex-volume-deployer
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: s3-fuse-flex-volume-deployer
      labels:
        app: s3-fuse-flex-volume-deployer
    spec:
      initContainers:
        - name: install-host-deps
          image: busybox:latest
          imagePullPolicy: Always
          securityContext:
              privileged: true
          volumeMounts:
            - mountPath: /rootfs
              name: rootfs
          command:
            - sh
            - -c
            - chroot /rootfs yum update -y && chroot /rootfs amazon-linux-extras install python3 && chroot /rootfs yum install -y fuse git && chroot /rootfs pip3 install git+git://github.com/met-office-lab/pysssix.git@big_cache && chroot /rootfs curl -L -o /usr/bin/goofys http://bit.ly/goofys-latest && chroot /rootfs chmod +x /usr/bin/goofys
        - name: s3-flex-volume-drivers-deploy
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          securityContext:
              privileged: true
          volumeMounts:
            - mountPath: /flexmnt
              name: flexvolume-plugindir
            - mountPath: /hostbin
              name: flexvolume-usrlocalbin
      containers:
        - name: pause
          image: gcr.io/google_containers/pause
      volumes:
        - name: flexvolume-plugindir
          hostPath:
            path: {{ .Values.flexVolume.pluginDir | quote }}
        - name: flexvolume-usrlocalbin
          hostPath:
            path: '/usr/local/bin'
        - name: rootfs
          hostPath:
            path: /
            type: Directory
